- maspsx/__init__.py
> Fix nop when jump+mult follows mflo

- maspsx/__init__.py
> Rework mflo/mfhi handler

- maspsx/__init__.py
> Fix missing nop after div/divu/rem when .set is encountered

- maspsx.py
- maspsx/__init__.py
> Add 'uses_gp' function

- maspsx/__init__.py
> li/lw combo that uses r_dest needs an nop

- maspsx/__init__.py
> Put .comm variables in .bss section

- maspsx/__init__.py
> Basic multi-line macro support

- .github/workflows/ci.yaml
- maspsx/__init__.py
- tests/test_nop.py
> Fix missing nops when not using --expand-div

- README.md
- maspsx.py
- maspsx/__init__.py
- tests/test_nop.py
Should close #https://github.com/mkst/maspsx/issues/28 via `--aspsx-version=2.21`
> --aspsx-version support

- maspsx/__init__.py
- tests/test_gp_rel.py
- tests/test_li.py
> Handle scenario when gp_rel symbol contains an offset

- maspsx/__init__.py
- tests/test_nop.py
> Fix missing remu nop

- maspsx/__init__.py
- tests/test_nop.py
> Fix missing nop after div with label

- maspsx/__init__.py
- tests/test_nop.py
> Handle "$Le1:" label

- maspsx.py
- maspsx/__init__.py
- tests/test_nop.py
- tests/test_sltu.py
> Control sltu/at behaviour based on aspsx version

- maspsx/__init__.py
- tests/test_nop.py
> Fix more missing macro nops

- maspsx/__init__.py
- tests/test_div.py
> Fix extraneous nop

- aspsx/test_addu_at.py
- maspsx/__init__.py
- tests/test_move.py
- tests/test_nop.py
> Expand move into addu

- maspsx.py
- maspsx/__init__.py
> Replace '-mcpu' with '-mtune' when passing arg to gnu as

- maspsx/__init__.py
- tests/test_at.py
> Fix missing nop between v0/at

- maspsx/__init__.py
- tests/test_at.py
> Fix another $at expansion nop

- maspsx/__init__.py
- tests/test_functions.py
> Handle "$Lb..:" label emited when -gcoff is used

- maspsx/__init__.py
- tests/test_nop.py
> Fix missing nop with %lo macro

- maspsx/__init__.py
- tests/test_mflo.py
> Ensure we add nops between mflo/mfhi and rem/remu

- maspsx/__init__.py
- tests/test_mflo.py
> Handle nop in mflo/mfhi after div expansion

- maspsx/__init__.py
- tests/test_mflo.py
> Handle mflo/mfhi/mult combo

- maspsx/__init__.py
- tests/test_mflo.py
> Fixup div-div-nop with label
